<?php
include '../db.php';

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    die("Unauthorized");
}

$user_id = $_SESSION['user_id'];
$resume_id = isset($_GET['id']) ? (int)$_GET['id'] : null;

if (!$resume_id) {
    die("Resume not found");
}

// Get resume
$result = $conn->query("SELECT * FROM resumes WHERE id = $resume_id AND user_id = $user_id");
if ($result->num_rows === 0) {
    die("Resume not found");
}

$resume = $result->fetch_assoc();
$ai_resume = $resume['ai_resume'];
$ats_score = $resume['ats_score'];

// Generate PDF - Simple HTML to text for now (can upgrade to dompdf later)
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="resume.pdf"');

// For MVP, we'll use a simple approach with file output
// In production, install dompdf via composer
// For now, we'll redirect to a print view

?>

<!DOCTYPE html>
<html>
<head>
    <title>Resume - PDF Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 8.5in;
            height: 11in;
            margin: 0;
            padding: 20px;
        }
        h1, h2 { margin: 10px 0 5px 0; }
        p { margin: 5px 0; }
    </style>
</head>
<body>
    <h1>Resume</h1>
    <hr>
    <div>
        <?php echo nl2br(htmlspecialchars($ai_resume)); ?>
    </div>
    <p style="font-size: 10px; color: gray; margin-top: 30px;">
        ATS Score: <?php echo $ats_score; ?>/100 | Generated by Resume AI
    </p>
</body>
</html>
